  - name: Install zabbix-agent repo
    yum:
      name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
      state: present

  - name: Install zabbix-agent
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - zabbix-agent
      - zabbix-get

  - name: Enable remote command
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '#AllowKey'
      insertbefore: "### Option: DenyKey"
      line: "AllowKey=system.run[*]"

  - name: Enable remote command
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      line: "EnableRemoteCommands=1 "

  - name: Enable remote command(2)
    blockinfile:
      path: /etc/sudoers
      insertafter: '^root'
      block: |
        # allows 'zabbix' user to run all commands without password.
        zabbix ALL=NOPASSWD: ALL
      validate: '/usr/sbin/visudo -cf %s'

  - name: Define Server
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: "^Server="
      line: "Server={{ server_name }}"

  - name: Define ServerActive
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: "^ServerActive="
      line: "ServerActive={{ server_name }}"

  - name: Define Hostname
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: "^Hostname="
      line: "Hostname={{ hostname }}"

  - name: edit login shell for zabbix-user
    user: 
      name: zabbix
      shell: /bin/bash


  - name: Restart zabbix-agent
    systemd:
      name: zabbix-agent
      state: restarted
      enabled: yes
      daemon_reload: yes
